package demo.sd.redhat.com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-720038
 * 2019-01-29T04:57:29.819+04:00
 * Generated source version: 3.1.11.fuse-720038
 * 
 */
@WebServiceClient(name = "AccountService", 
                  wsdlLocation = "http://127.0.0.1:8081/ws/accountService?wsdl",
                  targetNamespace = "http://com.redhat.sd.demo/") 
public class AccountService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com.redhat.sd.demo/", "AccountService");
    public final static QName AccountServicePort = new QName("http://com.redhat.sd.demo/", "AccountServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8081/ws/accountService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccountService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8081/ws/accountService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccountService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccountService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AccountService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AccountService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AccountService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServicePort")
    public AccountService getAccountServicePort() {
        return super.getPort(AccountServicePort, AccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServicePort")
    public AccountService getAccountServicePort(WebServiceFeature... features) {
        return super.getPort(AccountServicePort, AccountService.class, features);
    }

}
